version: "3"
networks:
  net:
    driver: bridge  
services:  
  postgres:
    networks:
      - net
    restart: on-failure
    image: f2hex/postgres
    container_name: postgres
    deploy:
       resources:
          limits:
             cpus: '1'
             memory: 256M
    environment:
      - POSTGRES_USER=redmine
      - POSTGRES_PASSWORD=secret
    volumes:
      - /data/redmine/db:/var/lib/postgresql/data
   

  redmine:
    networks:
      - net
    restart: on-failure
    image: redmine
    container_name: redmine
    deploy:
       resources:
          limits:
             cpus: '1'
             memory: 256M
    links:
      - postgres:db
    volumes:
      - /data/redmine/app/files:/usr/src/redmine/files
    depends_on:
      - postgres 
    

  nginx:
    networks:
      - net
    restart: on-failure
    image: nginx
    container_name: nginx
    deploy:
       resources:
          limits:
             cpus: '1'
             memory: 256M
    ports:
      - "81:80"
    volumes:
      - /data/redmine/web/log:/var/log/nginx
      - ./nginx.conf:/etc/nginx/nginx.conf:ro 
    depends_on:
      - redmine

