version: "3"
networks:
  net:
    driver: bridge  
services:  
  db_server:
    restart: on-failure
    image: f2hex/postgres
    container_name: redmine-db_server
    deploy:
       resources:
          limits:
             cpus: '1'
             memory: 256M
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - net
    volumes:
      - /data/redmine/db:/var/lib/postgresql/data
   

  app_server:
    restart: on-failure
    image: redmine
    container_name: redmine-app_server
    deploy:
       resources:
          limits:
             cpus: '1'
             memory: 256M
    networks:
      - net
    volumes:
      - /data/redmine/app/files:/usr/src/redmine/files
    

  web_server:
    restart: on-failure
    image: nginx
    container_name: redmine-web_server
    deploy:
       resources:
          limits:
             cpus: '1'
             memory: 256M
    ports:
      - "80:443"
    networks:
      - net
    volumes:
      - /data/redmine/web/log:/var/log/nginx
